#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, then to use that shell, set the "SHELL" environment variable to
#       that shell here.
#
#   (2) The slickness of a shell script is largely what it looks like, so this
#       script appears in several bash/csh scraped off the web with different
#       sed attempts. Just accept it. It works.
#
#  (3) This script is generated from the Gradle 'wrapper' task. The Gradle
#       'wrapper' task generates a script that allows you to build your Gradle
#       project without having to install Gradle on your system.
#
#       Important for running on Windows:
#
#  (4) Although the codebase is in Groovy, when compiled to bytecode to start
#       gradle, the "basedir" parameter (like a quoted string) will be treated as
#       backslash escapes.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}	# remove leading ...
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
export APP_NAME
export APP_BASE_NAME

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/bin/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/bin/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
    case $- in #(
      *i*) ;;
      *) MAX_FD_LIMIT=$( ulimit -H -n ) ;;
    esac
    if [ $MAX_FD_LIMIT != 'unlimited' ] ; then
        ulimit -n $MAX_FD_LIMIT || warn "Could not set maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...sysproperties
#   * --module-path
#   * the path to the gradle jar

# For Cygwin or MSYS, switch paths to Windows format before running java:
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kinda tricky, so let's do it in bash...
    local command_eval="false"
    local -a args
    local windows_path
    local windows_arg
    for arg in "$@" ; do
        if [ "$command_eval" = 'false' ] ; then
            case "$arg" in
                --)    command_eval='true' ;;
                /*)    windows_path=$( cygpath --path --windows "$arg" )
                       args+=( -D"org.gradle.appname=${APP_BASE_NAME%.*}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$windows_path" )
                       continue
                       ;;
                *)     args+=( "$arg" ) ;;
            esac
        fi
    done
    set -- "${args[@]}"

fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$( save "$@" )
JAVA_OPTS="$JAVA_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

# Collect all arguments for the java command, and put them in
#   the shell variable JAVA_OPTS
# which is used to call a shell SCRIPT, so we need to use eval.

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"